language: node_js
node_js:
  - "8"
  - "9"
  - "10"
env:
  - NODE_ENV="local"
before_install:
  - npm update -q
install:
  - npm i
script:
  - npm run lint
  - npm run test
  - npm run coveralls
after_script:
  - npm run coverage
  - cat ./coverage/lcov.info | codacy-coverage --accountToken COVERALLS_TOKEN --username COVERALLS_USERNAME --projectName mail-sc.js
